swagger: "2.0"
info:
  version: "1.0.0"
  title: "Example API"
  description: "An example API to query data and display it in Swagger"
host: "localhost:3000"
basePath: "/"
schemes:
  - "http"
paths:
  /users:
    get:
      summary: "Query and display data"
      description: "Query data from the database and display it."
      responses:
        "200":
          description: "Successful operation"
          schema:
            type: "object"
            properties:
              data:
                type: "array"
                items:
                  $ref: "#/definitions/Person"
definitions:
  Person:
    type: "object"
    properties:
      id:
        type: "integer"
      name:
        type: "string"
      age:
        type: "integer"
